config_version = 13

[backdrop]
enabled = true
tint_intensity = 0.0

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.0
    border = "on_hover"
    capsule = true
    capsule_opacity = 0.68999998457729816
    capsule_thickness = 0.67999998852610588
    center = [ "clock", "date", "weather", "notes" ]
    contact_shadow = true
    end = [ "media", "tray", "notifications", "clipboard", "network", "bluetooth", "battery", "session" ]
    font_family = "JetBrainsMono NF"
    margin_ends = 20
    padding = 0
    start = [ "launcher", "workspaces", "active_window", "cpu", "ram" ]
    thickness = 40

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[dock]
active_monitor_only = true
enabled = true
reserve_space = false
smart_auto_hide = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@winit",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 823.0
    cy = 613.5
    output = "eDP-1"
    placement_height = 1029.0
    placement_width = 1646.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 720.0
    cx = 654.0
    cy = 1435.0
    output = "winit"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 128.0
    box_width = 288.0
    cx = 743.0
    cy = 306.5
    output = "eDP-1"
    placement_height = 1029.0
    placement_width = 1646.0
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1047.0
    cy = 306.5
    output = "eDP-1"
    placement_height = 1029.0
    placement_width = 1646.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"

[plugin_settings."cleboost/hotspot"]
interface = "qwerty"
password = "12345678"

[plugin_settings."dotnetrob/cat"]
panel_placement = "floating"

[plugins]
auto_update = "all"
enabled = [ "noctalia/screen_recorder", "noctalia/notes", "raycursive/niri-displays" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
external_ip_enabled = true
font_family = "JetBrainsMono NF"
launch_apps_as_systemd_services = true
panel_anchor_bar = "default"
password_style = "random"
polkit_agent = true

    [shell.panel]
    control_center_placement = "floating"
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true

[theme]
builtin = "Noctalia"
mode = "auto"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[wallpaper.default]
path = "/home/nero/Pictures/Wallpapers/0F94F7CA7609B724ABAE87D68CD0A698.png"

[wallpaper.last]
path = "/home/nero/Pictures/Wallpapers/0F94F7CA7609B724ABAE87D68CD0A698.png"

[wallpaper.monitors.eDP-1]
path = "/home/nero/Pictures/Wallpapers/0F94F7CA7609B724ABAE87D68CD0A698.png"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/nero/Pictures/Wallpapers/【哲风壁纸】休闲装-动漫人物.png"
theme_mode = "light"
wallpaper_scheme = "m3-content"

[[wallpaper.favorite]]
path = "/home/nero/Pictures/Wallpapers/0F94F7CA7609B724ABAE87D68CD0A698.png"
theme_mode = "auto"

[[wallpaper.favorite]]
path = "/home/nero/Pictures/Wallpapers/girl.jpg"
theme_mode = "auto"

[widget.date]
capsule = true

[widget.media]
hide_when_no_media = true

[widget.notes]
type = "noctalia/notes:notes"