# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0e2e8"

# Title color for boxes
theme[title]="#42a5f5"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#8ab4f8"

# Background color of selected item in processes box
theme[selected_bg]="#42a5f5"

# Foreground color of selected item in processes box
theme[selected_fg]="#000000"

# Color of inactive/disabled text
theme[inactive_fg]="#c2c7cf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#8ab4f8"

# Cpu box outline color
theme[cpu_box]="#8c9199"

# Memory/disks box outline color
theme[mem_box]="#8c9199"

# Net up/down box outline color
theme[net_box]="#8c9199"

# Processes box outline color
theme[proc_box]="#8c9199"

# Box divider line and small boxes line color
theme[div_line]="#42474e"

# Temperature graph colors
theme[temp_start]="#8ab4f8"
theme[temp_mid]="#42a5f5"
theme[temp_end]="#f2b8b5"

# CPU graph colors
theme[cpu_start]="#8ab4f8"
theme[cpu_mid]="#42a5f5"
theme[cpu_end]="#f2b8b5"

# Mem/Disk free meter
theme[free_start]="#8ab4f8"
theme[free_mid]=""
theme[free_end]="#272a2f"

# Mem/Disk cached meter
theme[cached_start]="#8ab4f8"
theme[cached_mid]=""
theme[cached_end]="#272a2f"

# Mem/Disk available meter
theme[available_start]="#42a5f5"
theme[available_mid]=""
theme[available_end]="#0d47a1"

# Mem/Disk used meter
theme[used_start]="#f2b8b5"
theme[used_mid]=""
theme[used_end]="#8c1d18"

# Download graph colors
theme[download_start]="#8ab4f8"
theme[download_mid]="#42a5f5"
theme[download_end]="#8ab4f8"

# Upload graph colors
theme[upload_start]="#8ab4f8"
theme[upload_mid]="#42a5f5"
theme[upload_end]="#8ab4f8"
