#!/usr/bin/env python3
"""Generate Morandi-style color palette from Noctalia's Material You colors and apply to system."""

import json
import colorsys
import os
import re
import sys
import subprocess
import argparse
from pathlib import Path

NOCTALIA_COLORS = Path.home() / ".config/noctalia/colors.json"
NIRI_COLORS_KDL = Path.home() / ".config/niri/cfg/colors.kdl"
STARSHIP_TOML = Path.home() / ".config/starship.toml"
FCITX5_THEME = Path.home() / ".local/share/fcitx5/themes/morandi/theme.conf"
FASTFETCH_CONFIG = Path.home() / ".config/fastfetch/config.jsonc"
ALACRITTY_TOML = Path.home() / ".config/alacritty/alacritty.toml"
KDE_OUTPUT = Path.home() / ".local/share/color-schemes/Morandi-dark.colors"
NVIM_MORANDI = Path.home() / ".config/nvim/colors/morandi.lua"
GTK3_DIR = Path.home() / ".config/gtk-3.0"
GTK4_DIR = Path.home() / ".config/gtk-4.0"
GTK_WIDGETS_IMPORT = '@import url("morandi-widgets.css");'

def hex_to_hsl(hex_color):
    r = int(hex_color[1:3], 16) / 255
    g = int(hex_color[3:5], 16) / 255
    b = int(hex_color[5:7], 16) / 255
    h, l, s = colorsys.rgb_to_hls(r, g, b)
    return h * 360, s * 100, l * 100

def hsl_to_hex(h, s, l):
    h = h % 360
    s = max(0, min(100, s)) / 100
    l = max(0, min(100, l)) / 100
    r, g, b = colorsys.hls_to_rgb(h / 360, l, s)
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"

def morandi(hex_color, sat_reduction=0.3, light_adjust=0, warm_shift=0, sat_cap=45):
    h, s, l = hex_to_hsl(hex_color)
    s = s * (1 - sat_reduction)
    h = (h + warm_shift) % 360
    l = max(0, min(100, l + light_adjust))
    s = min(s, sat_cap)
    return hsl_to_hex(h, s, l)

def blend(c1, c2, ratio=0.5):
    r1, g1, b1 = int(c1[1:3], 16), int(c1[3:5], 16), int(c1[5:7], 16)
    r2, g2, b2 = int(c2[1:3], 16), int(c2[3:5], 16), int(c2[5:7], 16)
    r = int(r1 + (r2 - r1) * ratio)
    g = int(g1 + (g2 - g1) * ratio)
    b = int(b1 + (b2 - b1) * ratio)
    return f"#{r:02x}{g:02x}{b:02x}"

def generate_palette(c):
    p = {}
    primary = c.get("mPrimary", c.get("primary"))
    secondary = c.get("mSecondary", c.get("secondary"))
    tertiary = c.get("mTertiary", c.get("tertiary"))
    error = c.get("mError", c.get("error"))
    surface = c.get("mSurface", c.get("surface"))
    on_surface = c.get("mOnSurface", c.get("on_surface"))
    surface_var = c.get("mSurfaceVariant", c.get("surface_variant"))
    outline = c.get("mOutline", c.get("outline"))

    p["base"] = morandi(surface, 0.5, -2)
    p["mantle"] = morandi(surface, 0.6, -5)
    p["surface0"] = morandi(surface_var, 0.4, 2)
    p["surface1"] = morandi(surface_var, 0.3, 5)
    p["surface2"] = morandi(surface_var, 0.2, 8)
    p["overlay0"] = morandi(outline, 0.3, -2)
    p["overlay1"] = morandi(outline, 0.2, 2)
    p["overlay2"] = morandi(outline, 0.1, 5)
    p["subtext0"] = morandi(on_surface, 0.4, -8)
    p["subtext1"] = morandi(on_surface, 0.3, -4)
    p["text"] = morandi(on_surface, 0.2, 0)
    p["love"] = morandi(error, 0.25, -15)
    p["rose"] = morandi(blend(primary, error, 0.6), 0.3, -15, 5)
    p["gold"] = morandi(blend(primary, "#d4a574", 0.3), 0.35, -10, 15)
    p["peach"] = morandi(blend(error, "#d4a574", 0.4), 0.3, -10, 10)
    p["pine"] = morandi(tertiary, 0.3, -18, -5)
    p["foam"] = morandi(secondary, 0.35, -18, -5)
    p["iris"] = morandi(primary, 0.25, -18)
    p["sky"] = morandi(tertiary, 0.35, -18, -10)

    h, s, l = hex_to_hsl(p["surface1"])
    p["fcitx5_bg"] = hsl_to_hex(h, s * 0.6, min(l, 20))
    p["fcitx5_bg_alt"] = hsl_to_hex(h, s * 0.5, min(l + 3, 22))
    ih, is_, il = hex_to_hsl(p["iris"])
    p["fcitx5_hl_bg"] = hsl_to_hex(ih, is_, min(il, 38))
    p["fcitx5_text"] = p["text"]
    p["fcitx5_hl_text"] = p["base"]
    return p

def write_niri(palette):
    kdl = f"""// Auto-generated by morandi-gen.py — do not edit manually
layout {{
    focus-ring {{
        width 2
        active-gradient from="#42a5f5" to="#1e88e5" angle=45
        inactive-gradient from="{palette['surface0']}" to="{palette['surface1']}" angle=45
    }}
    border {{
        off
    }}
    shadow {{
        color "{palette['surface0']}70"
    }}
    tab-indicator {{
        active-color "{palette['iris']}"
        inactive-color "{palette['surface1']}"
        urgent-color "{palette['love']}"
    }}
    insert-hint {{
        color "{palette['iris']}80"
    }}
}}
recent-windows {{
    highlight {{
        active-color "{palette['iris']}"
        urgent-color "{palette['love']}"
    }}
}}
"""
    with open(NIRI_COLORS_KDL, "w") as f:
        f.write(kdl)

def write_starship(palette):
    if not STARSHIP_TOML.exists(): return
    with open(STARSHIP_TOML, "r") as f:
        content = f.read()
    keys = ["base", "mantle", "surface0", "surface1", "surface2", "overlay0", "overlay1", "overlay2", "subtext0", "subtext1", "text", "love", "gold", "peach", "rose", "pine", "foam", "iris", "sky"]
    new_palette = "[palettes.custom]\n" + "\n".join(f"{k} = '{palette[k]}'" for k in keys) + "\n"
    content, count = re.subn(r"\[palettes\.custom\][\s\S]*?(?=\n\[|\Z)", new_palette, content)
    if count == 0: content += "\n" + new_palette
    with open(STARSHIP_TOML, "w") as f:
        f.write(content)

def write_fcitx5(palette):
    theme_dir = FCITX5_THEME.parent
    theme_dir.mkdir(parents=True, exist_ok=True)
    tray_outline, tray_text = palette["surface0"], palette["text"]
    bg, hl = palette['fcitx5_bg'], palette['fcitx5_hl_bg']
    bh, bs, bl = hex_to_hsl(bg)
    border = hsl_to_hex(bh, bs, min(bl + 5, 100))
    hh, hs, hl_val = hex_to_hsl(hl)
    hborder = hsl_to_hex(hh, hs, min(hl_val + 5, 100))
    
    panel_svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="40" height="100"><g><rect width="39" height="99" x=".5" y=".5" fill="{bg}" stroke="{border}" rx="10" ry="10"/></g></svg>'
    highlight_svg = f'<svg xmlns="http://www.w3.org/2000/svg" width="39" height="44"><g><rect width="39" height="44" x="0" y="0" fill="{hl}" stroke="{hborder}" stroke-width="0" rx="8" ry="8"/></g></svg>'
    
    with open(theme_dir / "panel.svg", "w") as f: f.write(panel_svg)
    with open(theme_dir / "highlight.svg", "w") as f: f.write(highlight_svg)
    
    theme = f"""[Metadata]
Name=morandi
Version=0.0.3
Author=morandi-gen
Description=Auto-generated Morandi theme

[InputPanel]
NormalColor={palette['fcitx5_text']}
HighlightColor={palette['fcitx5_hl_text']}
HighlightBackgroundColor={palette['fcitx5_hl_bg']}
HighlightCandidateColor={palette['fcitx5_text']}
EnableBlur=True
FullWidthHighlight=True
PageButtonAlignment=Bottom
[InputPanel/BlurMargin]
Left=0\nRight=0\nTop=0\nBottom=0
[InputPanel/Background]
Image=panel.svg
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}
BorderWidth=0
[InputPanel/Background/Margin]
Left=6\nRight=6\nTop=6\nBottom=6
[InputPanel/Highlight]
Image=highlight.svg
Color={palette['fcitx5_hl_bg']}
BorderColor={palette['fcitx5_hl_bg']}00
BorderWidth=0
[InputPanel/Highlight/Margin]
Left=4\nRight=4\nTop=3\nBottom=3
[InputPanel/TextMargin]
Left=8\nRight=8\nTop=4\nBottom=4
[Menu]
NormalColor={palette['fcitx5_text']}
HighlightCandidateColor={palette['fcitx5_text']}
Spacing=0
[Menu/Background]
Image=panel.svg
Color={palette['fcitx5_bg']}
BorderColor={palette['fcitx5_bg']}00
BorderWidth=0
[Menu/Background/Margin]
Left=4\nRight=4\nTop=4\nBottom=4
[Menu/Highlight]
Image=highlight.svg
Color={palette['fcitx5_hl_bg']}
BorderColor={palette['fcitx5_hl_bg']}00
BorderWidth=0
[Menu/Highlight/Margin]
Left=2\nRight=2\nTop=1\nBottom=1
[Menu/Separator]
Color={palette['fcitx5_bg_alt']}
BorderColor={palette['fcitx5_bg_alt']}00
BorderWidth=0
"""
    with open(FCITX5_THEME, "w") as f: f.write(theme)
    classicui = Path.home() / ".config/fcitx5/conf/classicui.conf"
    if classicui.exists():
        content = classicui.read_text()
        content = re.sub(r"^Theme=.*", "Theme=morandi", content, flags=re.MULTILINE)
        content = re.sub(r"^DarkTheme=.*", "DarkTheme=morandi", content, flags=re.MULTILINE)
        content = re.sub(r"^UseDarkTheme=.*", "UseDarkTheme=False", content, flags=re.MULTILINE)
        content = re.sub(r"^TrayOutlineColor=.*", f"TrayOutlineColor={tray_outline}", content, flags=re.MULTILINE)
        content = re.sub(r"^TrayTextColor=.*", f"TrayTextColor={tray_text}", content, flags=re.MULTILINE)
        classicui.write_text(content)

def write_fastfetch(palette):
    if not FASTFETCH_CONFIG.exists():
        return
    content = FASTFETCH_CONFIG.read_text()

    content = re.sub(
        r'"color"\s*:\s*\{[^}]*\}',
        f'"color": {{ "keys": "{palette["iris"]}", "title": "{palette["text"]}" }}',
        content,
    )

    if '"disk"' not in content:
        content = content.replace(
            '{ "type": "memory", "key": " \uf0e4 Memory" }',
            '{ "type": "memory", "key": " \uf0e4 Memory" }, { "type": "disk", "key": " \uf0a0 Disk" }',
        )

    FASTFETCH_CONFIG.write_text(content)

ALACRITTY_ORIGINAL_NORMAL = {"black": "#1c1c1c", "red": "#ff6c6b", "green": "#98be65", "yellow": "#ecbe7b", "blue": "#51afef", "magenta": "#c678dd", "cyan": "#46d9ff", "white": "#bbc2cf"}
ALACRITTY_ORIGINAL_BRIGHT = {"black": "#5b6268", "red": "#da8548", "green": "#4db5bd", "yellow": "#ecbe7b", "blue": "#3071db", "magenta": "#a9a1e1", "cyan": "#46d9ff", "white": "#dfdfdf"}

def write_alacritty():
    if not ALACRITTY_TOML.exists(): return
    content = ALACRITTY_TOML.read_text()
    normal_colors = "\n".join(f'{k} = "{morandi(v, 0.45, -5, 0, 40)}"' for k, v in ALACRITTY_ORIGINAL_NORMAL.items())
    bright_colors = "\n".join(f'{k} = "{morandi(v, 0.45, -5, 0, 40)}"' for k, v in ALACRITTY_ORIGINAL_BRIGHT.items())
    content = re.sub(r"\[colors\.normal\]\n(.*?\n)+?(?=\[colors\.bright\])", f"[colors.normal]\n{normal_colors}\n", content, flags=re.MULTILINE)
    content = re.sub(r"\[colors\.bright\]\n(.*?\n)+?(?=\[colors\.cursor\])", f"[colors.bright]\n{bright_colors}\n", content, flags=re.MULTILINE)
    ALACRITTY_TOML.write_text(content)

def hex_to_rgb(hex_color):
    h = hex_color.lstrip("#")
    return int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)


def write_kde(colors):
    def rgb_str(c): return f"{c[0]},{c[1]},{c[2]}"
    bg, surface, surface_var = hex_to_rgb(colors["background"]), hex_to_rgb(colors["surface_container"]), hex_to_rgb(colors["surface_variant"])
    primary, primary_cont = hex_to_rgb(colors["primary"]), hex_to_rgb(colors["primary_container"])
    on_surface, on_surface_var, on_primary = hex_to_rgb(colors["on_surface"]), hex_to_rgb(colors["on_surface_variant"]), hex_to_rgb(colors["on_primary"])
    error, window_bg = hex_to_rgb(colors["error"]), hex_to_rgb(colors["surface_container_low"])
    content = f"""[General]\nName=Morandi Dark\nshadeSortColumn=true\n
[Colors:Button]
BackgroundNormal={rgb_str(surface)}\nBackgroundAlternate={rgb_str(surface)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:View]
BackgroundNormal={rgb_str(bg)}\nBackgroundAlternate={rgb_str(surface_var)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:Window]
BackgroundNormal={rgb_str(window_bg)}\nBackgroundAlternate={rgb_str(window_bg)}
ForegroundNormal={rgb_str(on_surface)}\nForegroundInactive={rgb_str(on_surface_var)}
ForegroundActive={rgb_str(primary)}\nForegroundLink={rgb_str(primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[Colors:Selection]
BackgroundNormal={rgb_str(primary_cont)}\nBackgroundAlternate={rgb_str(primary_cont)}
ForegroundNormal={rgb_str(on_primary)}\nForegroundInactive={rgb_str(on_primary)}\nForegroundActive={rgb_str(on_primary)}
ForegroundLink={rgb_str(on_primary)}\nForegroundNegative={rgb_str(error)}
DecorationFocus={rgb_str(primary_cont)}\nDecorationHover={rgb_str(primary)}
[WM]
activeBackground={rgb_str(surface)}\nactiveForeground={rgb_str(on_surface)}
inactiveBackground={rgb_str(bg)}\ninactiveForeground={rgb_str(on_surface_var)}
activeTitleBtnBg={rgb_str(primary_cont)}\ninactiveTitleBtnBg={rgb_str(surface)}\n"""
    KDE_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    KDE_OUTPUT.write_text(content)

def write_blender(palette):
    script_content = f"""import bpy
theme = bpy.context.preferences.themes[0]
theme.name = "Morandi"
def h(hx): return [int(hx.lstrip('#')[i:i+2], 16)/255.0 for i in (0, 2, 4)]
bg, fg, accent, bg_light, bg_dark = h('{palette['base']}'), h('{palette['text']}'), h('{palette['iris']}'), h('{palette['surface0']}'), h('{palette['mantle']}')
def s(o, a, c):
    try: setattr(o, a, tuple(c + [1.0]) if len(getattr(o, a)) == 4 else tuple(c))
    except: pass
spaces = [getattr(theme, n).space if hasattr(getattr(theme, n), 'space') else getattr(theme, n) for n in dir(theme) if not n.startswith('_') and (hasattr(getattr(theme, n), 'space') or hasattr(getattr(theme, n), 'back'))]
for sp in spaces:
    if hasattr(sp, 'back'): s(sp, 'back', bg)
    if hasattr(sp, 'text'): s(sp, 'text', fg)
    if hasattr(sp, 'header'): s(sp, 'header', bg)
    if hasattr(sp, 'header_text'): s(sp, 'header_text', fg)
    if hasattr(sp, 'panelcolors'):
        s(sp.panelcolors, 'header', bg_light); s(sp.panelcolors, 'back', bg)
v3 = theme.view_3d
if hasattr(v3, 'space') and hasattr(v3.space, 'gradients'): s(v3.space.gradients, 'high_gradient', bg)
ui = theme.user_interface
for w in [ui.wcol_regular, ui.wcol_tool, ui.wcol_text, ui.wcol_option, ui.wcol_menu, ui.wcol_pulldown, ui.wcol_tab]:
    if hasattr(w, 'inner'): s(w, 'inner', bg_light)
    if hasattr(w, 'inner_sel'): s(w, 'inner_sel', accent)
    if hasattr(w, 'item'): s(w, 'item', fg)
    if hasattr(w, 'text'): s(w, 'text', fg)
bpy.ops.wm.save_userpref()
"""
    import tempfile
    with tempfile.NamedTemporaryFile('w', suffix='.py', delete=False) as f:
        f.write(script_content)
        temp_path = f.name
    subprocess.run(["blender", "-b", "-P", temp_path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    os.remove(temp_path)

def write_godot(palette):
    godot_settings = list(Path.home().glob(".config/godot/editor_settings-*.tres"))
    if not godot_settings: return
    
    def hex_to_color(hex_str):
        hex_str = hex_str.lstrip('#')
        r, g, b = (int(hex_str[i:i+2], 16)/255.0 for i in (0, 2, 4))
        return f"Color({r:.3f}, {g:.3f}, {b:.3f}, 1)"
        
    base_color = hex_to_color(palette["base"])
    accent_color = hex_to_color(palette["iris"])
    
    for path in godot_settings:
        content = path.read_text()
        content = re.sub(r'interface/theme/base_color\s*=\s*Color\([^)]+\)', f'interface/theme/base_color = {base_color}', content)
        content = re.sub(r'interface/theme/accent_color\s*=\s*Color\([^)]+\)', f'interface/theme/accent_color = {accent_color}', content)
        content = re.sub(r'interface/theme/color_preset\s*=\s*".*"', 'interface/theme/color_preset = "Custom"', content)
        path.write_text(content)

def write_obs(palette):
    obs_theme_dir = Path.home() / ".config/obs-studio/themes"
    obs_theme_dir.mkdir(parents=True, exist_ok=True)
    
    def rgb_str(hex_c):
        r, g, b = hex_to_rgb(hex_c)
        return f"rgb({r},{g},{b})"
        
    def darken(hex_c, amount=10):
        return morandi(hex_c, 0, -amount, 0, 100)

    obs_iris = darken(palette['iris'], 12)
    obs_foam = darken(palette['foam'], 12)
    obs_sky = darken(palette['sky'], 12)

    content = f"""@OBSThemeMeta {{
    name: 'Morandi';
    id: 'com.obsproject.Yami.Morandi';
    extends: 'com.obsproject.Yami';
    author: 'morandi-gen';
    dark: 'true';
}}

@OBSThemeVars {{
    --primary: {rgb_str(obs_iris)};
    --primary_light: {rgb_str(obs_foam)};
    --primary_lighter: {rgb_str(obs_sky)};
    --primary_dark: {rgb_str(palette['pine'])};
    --primary_darker: {rgb_str(palette['base'])};

    --blue1: {rgb_str(obs_sky)};
    --blue2: {rgb_str(obs_foam)};
    --blue3: {rgb_str(obs_iris)};
    --blue4: {rgb_str(palette['pine'])};
    --blue5: {rgb_str(palette['surface1'])};
    --blue6: {rgb_str(palette['surface0'])};

    --bg_base: {rgb_str(palette['mantle'])};
    --bg_window: {rgb_str(palette['base'])};
    --bg_preview: {rgb_str(palette['mantle'])};

    --border_color: {rgb_str(palette['surface1'])};

    --input_bg: {rgb_str(palette['surface0'])};
    --input_bg_hover: {rgb_str(palette['surface1'])};
    --input_bg_focus: {rgb_str(palette['surface1'])};

    --list_item_bg_selected: {rgb_str(palette['surface0'])};
    --list_item_bg_hover: {rgb_str(palette['surface1'])};

    --input_border: {rgb_str(palette['surface2'])};
    --input_border_hover: {rgb_str(obs_iris)};
    --input_border_focus: {rgb_str(obs_iris)};

    --button_bg: {rgb_str(palette['surface0'])};
    --button_bg_hover: {rgb_str(palette['surface1'])};
    --button_bg_down: {rgb_str(palette['surface2'])};
    --button_bg_disabled: {rgb_str(palette['mantle'])};

    --button_bg_red: {rgb_str(palette['love'])};
    --button_bg_red_hover: {rgb_str(palette['rose'])};
    --button_bg_red_down: {rgb_str(palette['love'])};

    --button_border: {rgb_str(palette['surface2'])};
    --button_border_hover: {rgb_str(obs_iris)};
    --button_border_focus: {rgb_str(obs_iris)};

    --tab_bg: {rgb_str(palette['surface0'])};
    --tab_bg_hover: {rgb_str(palette['surface1'])};
    --tab_bg_down: {rgb_str(palette['surface2'])};
    --tab_bg_disabled: {rgb_str(palette['mantle'])};

    --tab_border: {rgb_str(palette['surface0'])};
    --tab_border_hover: {rgb_str(palette['surface2'])};
    --tab_border_focus: {rgb_str(palette['surface2'])};
    --tab_border_selected: {rgb_str(obs_iris)};

    --scrollbar_handle: {rgb_str(palette['surface1'])};
    --scrollbar_hover: {rgb_str(palette['surface2'])};
    --scrollbar_down: {rgb_str(palette['surface0'])};
    --scrollbar_border: {rgb_str(palette['surface1'])};

    --toolbutton_bg: {rgb_str(palette['surface0'])};
    --toolbutton_bg_hover: {rgb_str(palette['surface1'])};
    --toolbutton_bg_down: {rgb_str(palette['surface2'])};
    --toolbutton_bg_disabled: {rgb_str(palette['mantle'])};
}}
"""
    (obs_theme_dir / "Yami_Morandi.ovt").write_text(content)
    
    obs_config = Path.home() / ".config/obs-studio/global.ini"
    if obs_config.exists():
        conf = obs_config.read_text()
        conf = re.sub(r"^CurrentTheme3=.*", "CurrentTheme3=Yami_Morandi", conf, flags=re.MULTILINE)
        obs_config.write_text(conf)

def write_clash_verge(palette):
    config_path = Path.home() / ".local/share/io.github.clash-verge-rev.clash-verge-rev/verge.yaml"
    if not config_path.exists():
        return

    content = config_path.read_text()

    css = f""":root {{
  --joy-palette-background-body: {palette['base']} !important;
  --joy-palette-background-surface: {palette['surface0']} !important;
  --joy-palette-background-level1: {palette['surface1']} !important;
  --joy-palette-background-level2: {palette['surface2']} !important;
  --joy-palette-background-level3: {palette['overlay0']} !important;
  --mui-palette-background-default: {palette['base']} !important;
  --mui-palette-background-paper: {palette['surface0']} !important;
  --bg-base: {palette['base']} !important;
  --bg-surface: {palette['surface0']} !important;
  --mui-palette-primary-contrastText: #ffffff !important;
  --joy-palette-primary-solidColor: #ffffff !important;
}}
body, #root, main, .MuiDrawer-paper, .MuiAppBar-root, .layout-content, .page, .page-content {{
  background-color: {palette['base']} !important;
  background-image: none !important;
  color: {palette['text']} !important;
}}
.MuiPaper-root, .MuiCard-root, .MuiDialog-paper, .MuiPopover-paper {{
  background-color: {palette['surface0']} !important;
  background-image: none !important;
  border-radius: 12px !important;
  border: 1px solid {palette['surface1']} !important;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15) !important;
}}
.Mui-selected, .Mui-selected *, .MuiButton-containedPrimary, .MuiButton-containedPrimary *, .clash-active {{
  color: #ffffff !important;
}}
* {{
  transition: background-color 0.4s cubic-bezier(0.4, 0, 0.2, 1), 
              border-color 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              color 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              box-shadow 0.4s cubic-bezier(0.4, 0, 0.2, 1),
              transform 0.3s cubic-bezier(0.4, 0, 0.2, 1) !important;
}}
.MuiButtonBase-root:hover, .MuiMenuItem-root:hover, .clash-hover-effect:hover {{
  transform: translateY(-2px) !important;
  box-shadow: 0 6px 16px rgba(0,0,0,0.2) !important;
}}
.MuiButtonBase-root:active, .MuiMenuItem-root:active, .clash-hover-effect:active {{
  transform: translateY(1px) !important;
  box-shadow: none !important;
}}"""

    css_indented = "\n    ".join(css.split("\n"))
    
    theme_setting = f"theme_setting:\n  primary_color: '{palette['iris']}'\n  secondary_color: '{palette['foam']}'\n  info_color: '{palette['sky']}'\n  error_color: '{palette['love']}'\n  warning_color: '{palette['gold']}'\n  success_color: '{palette['pine']}'\n  css_injection: |\n    {css_indented}"
    
    if "theme_setting: null" in content:
        content = re.sub(r"^theme_setting:\s*null", theme_setting, content, flags=re.MULTILINE)
    elif re.search(r"^theme_setting:", content, flags=re.MULTILINE):
        content = re.sub(r"^theme_setting:.*(\n\s+.*)*", theme_setting, content, flags=re.MULTILINE)
    else:
        content += "\n" + theme_setting + "\n"
        
    content = re.sub(r"^css_injection:.*(\n\s+.*)*", "", content, flags=re.MULTILINE).strip() + "\n"
        
    config_path.write_text(content)




def apply_system_changes(wallpaper_path=None):
    def run_ignore_missing(*args, **kwargs):
        try:
            subprocess.run(*args, **kwargs)
        except FileNotFoundError:
            pass

    env = os.environ.copy()
    env["DISPLAY"] = ":0"
    env["XDG_RUNTIME_DIR"] = f"/run/user/{os.getuid()}"
    run_ignore_missing(["dbus-send", "--session", "--dest=org.kde.plasmashell", "--type=method_call", "/PlasmaShell", "org.kde.PlasmaShell.evaluateScript", "string: var allDesktops = desktops(); for (var i=0; i<allDesktops.length; i++) { allDesktops[i].wallpaperPlugin = '' }"], env=env, stderr=subprocess.DEVNULL)
    run_ignore_missing(["qdbus", "org.kde.KWin", "/KWin", "reconfigure"], env=env, stderr=subprocess.DEVNULL)
    run_ignore_missing(["niri", "msg", "action", "load-config-file"], stderr=subprocess.DEVNULL)
    run_ignore_missing(["pkill", "-USR2", "cava"], stderr=subprocess.DEVNULL)
    
    if wallpaper_path and Path(wallpaper_path).exists():
        efi_dir = "/boot/efi"
        subprocess.run(["sudo", "magick", wallpaper_path, "-blur", "0x12", "-resize", "1920x1080!", "-quality", "95", f"{efi_dir}/limine_bg.png"], stderr=subprocess.DEVNULL)
        
    try:
        pid = subprocess.check_output(["pgrep", "-x", "fcitx5"]).decode().strip()
        if pid:
            subprocess.run(["kill", pid])
            subprocess.run(["sleep", "0.3"])
    except subprocess.CalledProcessError:
        pass
    subprocess.Popen(["fcitx5"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, start_new_session=True)

def write_flclash(palette):
    config_path = Path.home() / ".local/share/com.follow.clash/shared_preferences.json"
    if not config_path.exists():
        return
        
    try:
        with open(config_path, "r") as f:
            data = json.load(f)
            
        if "flutter.config" in data:
            flutter_config = json.loads(data["flutter.config"])
            
            hex_color = palette['iris'].lstrip('#')
            if len(hex_color) == 6:
                argb_int = int("ff" + hex_color, 16)
            else:
                argb_int = int(hex_color, 16)
                
            if "themeProps" not in flutter_config:
                flutter_config["themeProps"] = {}
                
            flutter_config["themeProps"]["primaryColor"] = argb_int
            flutter_config["themeProps"]["pureBlack"] = False
            flutter_config["themeProps"]["themeMode"] = "dark"
            
            data["flutter.config"] = json.dumps(flutter_config, separators=(',', ':'))
            
            with open(config_path, "w") as f:
                json.dump(data, f, separators=(',', ':'))
    except Exception as e:
        print(f"Failed to write flclash theme: {e}")

def write_cava(palette):
    cava_dir = Path.home() / ".config/cava"
    theme_dir = cava_dir / "themes"
    theme_dir.mkdir(parents=True, exist_ok=True)
    theme_path = theme_dir / "morandi"
    content = f"""; Auto-generated by morandi-gen.py — do not edit manually
[color]
background = 'default'
foreground = '{palette['iris']}'

gradient = 1
gradient_color_1 = '{palette['sky']}'
gradient_color_2 = '{palette['foam']}'
gradient_color_3 = '{palette['pine']}'
gradient_color_4 = '{palette['iris']}'
gradient_color_5 = '{palette['gold']}'
gradient_color_6 = '{palette['peach']}'
gradient_color_7 = '{palette['rose']}'
gradient_color_8 = '{palette['love']}'
"""
    theme_path.write_text(content)

def write_nvim(palette):
    if not NVIM_MORANDI.exists():
        return

    theme = {
        "bg": palette["mantle"],
        "bg_alt": palette["base"],
        "bg_highlight": palette["surface0"],
        "bg_visual": palette["surface1"],
        "bg_search": palette["surface2"],
        "fg": palette["text"],
        "fg_alt": palette["subtext1"],
        "fg_dim": palette["subtext0"],
        "fg_bright": blend(palette["text"], "#ffffff", 0.12),
        "rose": palette["rose"],
        "violet": palette["iris"],
        "mauve": palette["peach"],
        "pink": palette["love"],
        "green": palette["pine"],
        "blue": palette["sky"],
        "yellow": palette["gold"],
        "orange": palette["peach"],
        "red": palette["love"],
        "cyan": palette["foam"],
        "border": palette["surface2"],
        "border_highlight": palette["overlay1"],
    }

    for name, color in list(theme.items()):
        if name in {"bg", "bg_alt", "bg_highlight", "bg_visual", "bg_search", "fg", "fg_alt", "fg_dim", "fg_bright", "border", "border_highlight"}:
            continue
        theme[f"{name}_light"] = blend(color, "#ffffff", 0.16)
        theme[f"{name}_dark"] = blend(color, palette["mantle"], 0.28)

    content = NVIM_MORANDI.read_text()
    for name, color in theme.items():
        content, replacements = re.subn(
            rf'^(\s*{re.escape(name)}\s*=\s*)"#[0-9a-fA-F]{{6}}"',
            rf'\1"{color}"',
            content,
            flags=re.MULTILINE,
        )
        if replacements != 1:
            raise RuntimeError(f"Could not update Neovim palette entry: {name}")

    content, replacements = re.subn(
        r"^(\s*NeoTreeNormal\s*=\s*)\{[^}]*\},$",
        r"\1{ fg = p.fg },",
        content,
        flags=re.MULTILINE,
    )
    if replacements != 1:
        raise RuntimeError("Could not enable transparent NeoTreeNormal")

    content, replacements = re.subn(
        r"^(\s*NeoTreeNormalNC\s*=\s*)\{[^}]*\},$",
        r"\1{ fg = p.fg_alt },",
        content,
        flags=re.MULTILINE,
    )
    if replacements != 1:
        raise RuntimeError("Could not enable transparent NeoTreeNormalNC")

    NVIM_MORANDI.write_text(content)

_MORANDI_ICONS = {
    "check.svg": (
        '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">'
        '<path d="M3.4 8.3 6.7 11.6 12.6 4.7" fill="none" stroke="#000" '
        'stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round"/></svg>'
    ),
    "mixed.svg": (
        '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">'
        '<path d="M3.4 8h9.2" fill="none" stroke="#000" stroke-width="2.4" '
        'stroke-linecap="round"/></svg>'
    ),
    "dot.svg": (
        '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">'
        '<circle cx="8" cy="8" r="3.1" fill="#000"/></svg>'
    ),
}

# Selection-widget overrides shared by GTK3/GTK4 (colors injected via <TOKEN>)
_GTK_WIDGETS_COMMON = """
/* --- Reset Materia's 24px circular hit-area --- */
checkbutton check,
checkbutton check:hover,
checkbutton check:active,
radiobutton radio,
radiobutton radio:hover,
radiobutton radio:active {
  margin: 0;
  padding: 0;
  min-height: 20px;
  min-width: 20px;
  background-image: none;
  box-shadow: none;
  transition: 120ms ease;
}

/* --- Checkbox --- */
check {
  border-radius: 6px;
  border: 1px solid alpha(<OVERLAY0>, 0.55);
  background-color: alpha(<SURFACE1>, 0.5);
  -gtk-icon-source: none;
}
check:hover {
  border-color: alpha(<IRIS>, 0.65);
  background-color: alpha(<IRIS>, 0.14);
}
check:checked,
check:indeterminate {
  border-color: <IRIS>;
  background-color: <IRIS>;
  color: <BASE>;
  -gtk-icon-source: -gtk-recolor(url("morandi-icons/check.svg"));
}
check:indeterminate {
  -gtk-icon-source: -gtk-recolor(url("morandi-icons/mixed.svg"));
}
check:checked:hover,
check:indeterminate:hover,
check:checked:active,
check:indeterminate:active {
  border-color: <IRIS_BRIGHT>;
  background-color: <IRIS_BRIGHT>;
}
check:focus {
  box-shadow: 0 0 0 2px alpha(<IRIS>, 0.35);
}
check:disabled {
  border-color: alpha(<OVERLAY0>, 0.28);
  background-color: alpha(<SURFACE1>, 0.28);
}
check:checked:disabled,
check:indeterminate:disabled {
  border-color: alpha(<IRIS>, 0.32);
  background-color: alpha(<IRIS>, 0.32);
  color: alpha(<BASE>, 0.45);
}

/* --- Radio --- */
radio {
  border-radius: 9999px;
  border: 1px solid alpha(<OVERLAY0>, 0.55);
  background-color: alpha(<SURFACE1>, 0.5);
  -gtk-icon-source: none;
}
radio:hover {
  border-color: alpha(<IRIS>, 0.65);
  background-color: alpha(<IRIS>, 0.14);
}
radio:checked {
  border-color: <IRIS>;
  background-color: <IRIS>;
  color: <BASE>;
  -gtk-icon-source: -gtk-recolor(url("morandi-icons/dot.svg"));
}
radio:checked:hover,
radio:checked:active {
  border-color: <IRIS_BRIGHT>;
  background-color: <IRIS_BRIGHT>;
}
radio:focus {
  box-shadow: 0 0 0 2px alpha(<IRIS>, 0.35);
}
radio:disabled {
  border-color: alpha(<OVERLAY0>, 0.28);
  background-color: alpha(<SURFACE1>, 0.28);
}
radio:checked:disabled {
  border-color: alpha(<IRIS>, 0.32);
  background-color: alpha(<IRIS>, 0.32);
  color: alpha(<BASE>, 0.45);
}
"""

_GTK3_WIDGETS_CSS = _GTK_WIDGETS_COMMON + """
/* --- Small variants inside menus (GTK3/GTK4, identical styling) --- */
menu menuitem check,
menu menuitem radio,
menu menuitem check:hover,
menu menuitem check:active,
menu menuitem radio:hover,
menu menuitem radio:active,
popover modelbutton.flat check,
popover modelbutton.flat radio,
popover modelbutton.flat check:hover,
popover modelbutton.flat check:active,
popover modelbutton.flat radio:hover,
popover modelbutton.flat radio:active,
popover.menu check,
popover.menu radio,
popover.menu check:hover,
popover.menu check:active,
popover.menu radio:hover,
popover.menu radio:active {
  min-height: 16px;
  min-width: 16px;
  margin: 0;
  padding: 0;
  border-radius: 4px;
  border: 1px solid alpha(<OVERLAY0>, 0.4);
  background-color: transparent;
  background-image: none;
  box-shadow: none;
}
menu menuitem radio,
menu menuitem radio:hover,
menu menuitem radio:active,
popover modelbutton.flat radio,
popover modelbutton.flat radio:hover,
popover modelbutton.flat radio:active,
popover.menu radio,
popover.menu radio:hover,
popover.menu radio:active {
  border-radius: 9999px;
}
menu menuitem check:checked,
menu menuitem check:indeterminate,
menu menuitem radio:checked,
popover modelbutton.flat check:checked,
popover modelbutton.flat check:indeterminate,
popover modelbutton.flat radio:checked,
popover.menu check:checked,
popover.menu check:indeterminate,
popover.menu radio:checked {
  border-color: <IRIS>;
  background-color: <IRIS>;
  color: <BASE>;
}
menu menuitem check:checked:hover,
menu menuitem check:indeterminate:hover,
menu menuitem radio:checked:hover,
popover modelbutton.flat check:checked:hover,
popover modelbutton.flat check:indeterminate:hover,
popover modelbutton.flat radio:checked:hover,
popover.menu check:checked:hover,
popover.menu check:indeterminate:hover,
popover.menu radio:checked:hover {
  border-color: <IRIS_BRIGHT>;
  background-color: <IRIS_BRIGHT>;
}

/* --- Menu/popover row hover highlight --- */
menu menuitem:hover,
menu menuitem:focus,
.context-menu menuitem:hover,
popover modelbutton.flat:hover,
popover.menu modelbutton:hover {
  background-color: alpha(<IRIS>, 0.16);
}

/* --- Text selection --- */
textview text selection,
textview text selection:focus,
textview > text > selection,
textview > text > selection:focus,
entry selection,
entry selection:focus,
entry > text > selection,
entry > text > selection:focus,
label selection,
label selection:focus,
label > selection,
label > selection:focus,
.view selection,
.view selection:focus,
spinbutton:not(.vertical) selection,
spinbutton:not(.vertical) > text > selection {
  background-color: alpha(<IRIS>, 0.35);
}
"""

_GTK4_WIDGETS_CSS = _GTK3_WIDGETS_CSS

def write_gtk(palette):
    """Inject Morandi styling for GTK3/GTK4 selection widgets via user-level CSS."""
    ih, is_, il = hex_to_hsl(palette["iris"])
    iris_bright = hsl_to_hex(ih, min(is_ + 10, 100), min(il + 7, 100))

    colors = {
        "<IRIS>": palette["iris"],
        "<IRIS_BRIGHT>": iris_bright,
        "<BASE>": palette["base"],
        "<SURFACE1>": palette["surface1"],
        "<OVERLAY0>": palette["overlay0"],
    }

    css3, css4 = _GTK3_WIDGETS_CSS, _GTK4_WIDGETS_CSS
    for token, color in colors.items():
        css3 = css3.replace(token, color)
        css4 = css4.replace(token, color)
    css3 = "/* Auto-generated by morandi-gen.py - Morandi selection widgets (GTK3) */\n" + css3
    css4 = "/* Auto-generated by morandi-gen.py - Morandi selection widgets (GTK4) */\n" + css4

    for gtk_dir in (GTK3_DIR, GTK4_DIR):
        icon_dir = gtk_dir / "morandi-icons"
        icon_dir.mkdir(parents=True, exist_ok=True)
        for name, svg in _MORANDI_ICONS.items():
            (icon_dir / name).write_text(svg)

    (GTK3_DIR / "morandi-widgets.css").write_text(css3)
    (GTK4_DIR / "morandi-widgets.css").write_text(css4)

    for css_path in (GTK3_DIR / "gtk.css", GTK4_DIR / "gtk.css"):
        if not css_path.exists():
            css_path.write_text(GTK_WIDGETS_IMPORT + "\n")
            continue
        content = css_path.read_text()
        if GTK_WIDGETS_IMPORT.strip() in content:
            continue
        lines = content.splitlines()
        insert_at = 0
        for i, line in enumerate(lines):
            if line.strip().startswith("@import"):
                insert_at = i + 1
            else:
                break
        lines.insert(insert_at, GTK_WIDGETS_IMPORT.strip())
        css_path.write_text("\n".join(lines) + "\n")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--wallpaper", help="Path to current wallpaper for limine sync")
    args = parser.parse_args()

    if not NOCTALIA_COLORS.exists():
        print(f"Error: {NOCTALIA_COLORS} not found")
        sys.exit(1)

    with open(NOCTALIA_COLORS) as f:
        colors = json.load(f)

    palette = generate_palette(colors)
    write_niri(palette)
    write_starship(palette)
    write_fcitx5(palette)
    write_fastfetch(palette)
    write_alacritty()
    write_kde(colors)
    write_clash_verge(palette)
    write_flclash(palette)
    write_nvim(palette)
    write_gtk(palette)
    
    try:
        write_cava(palette)
    except Exception as e:
        print(f"Failed to write cava theme: {e}")
    
    try:
        write_blender(palette)
    except Exception as e:
        print(f"Failed to write blender theme: {e}")
        
    try:
        write_godot(palette)
    except Exception as e:
        print(f"Failed to write godot theme: {e}")
        

    try:
        write_obs(palette)
    except Exception as e:
        print(f"Failed to write obs theme: {e}")

    apply_system_changes(args.wallpaper)
    print("Morandi theme generated and system changes applied successfully.")

if __name__ == "__main__":
    main()
